### ISSUE TITLE
magento2 module coming?

### ISSUE THREAD

**Issue by futtta** [Tealium/integration-magento2#1]
We are working a major ecommerce project on Magento2 in Belgium and would like to integrate Tealium. I was happy to find integration-magento2, but the repo is empty. Do you have an ETA for a first version (even if "beta" or even "alpha")?

**Comment by jalakoo** [comment]
@futtta Thanks for reaching out.  This module is actively being work on and should be available before the end of Q4 2016.

**Comment by futtta** [comment]
hmmm, that doesn't really fit with our timeframe I'm afraid, in our planning tealium integration is foreseen for end oct/beginning of nov (and go live in jan).  any way for us to join a beta, might even help you guys? :-) 

if you want, you can contact me "offline" via frank-dot-goossens-at-techmahindra-dot-com to discuss possibilities!

**Comment by chrisanderberg** [comment]
Hi @futtta , thanks for the interest in our Magento 2 integration. I'll contact you directly to begin a discussion on the steps we can take forward.
