### ISSUE TITLE
setup:di:compile Class Not Found Error

### ISSUE THREAD

**Issue by RamblinDan** [Tealium/integration-magento2#2]
Hello,

After installing the extension I ran:

`bin/magento setup:di:compile`

This consistently results in a fatal error:

> Fatal error: Class 'Tealium\Tags\Block\Udo' not found in [magento-root]/vendor/tealium/tags/Block/DefaultUdo.php on line 6

**Comment by chrisanderberg** [comment]
Hi RamblinDan,

Did you install the extension using composer, or did you install it using the manual method as described in the readme?

-Chris

**Comment by RamblinDan** [comment]
@chrisanderberg Using composer.

**Comment by chrisanderberg** [comment]
@RamblinDan Okay, chances are the extension files are located in a different directory than where the setup:di:compile command is expecting them. The two locations would be [magento-root]/vendor/Tealium/Tags, and [magento-root]/app/code/Tealium/Tags. Can you verify in which directory your extension files exist?

**Comment by RamblinDan** [comment]
@chrisanderberg The composer install placed them in [magento-root]/vendor/tealium/tags

**Comment by chrisanderberg** [comment]
@RamblinDan  It appears you're running into the same issue I do when trying to install with Composer. Unfortunately I haven't been able to figure out the cause of it, and there seems to be no documentation or information on the web that's helpful. I'll continue to look into it further and try to get a solution. Another option may be to follow the manual installation as described in the readme, which will instead install the extension in [magento-root]/app/code/Tealium/Tags. It's not ideal and composer would be the preferred way, but unfortunately lack of documentation and information has me stuck. I'll update you when I have more information on the issue.

**Comment by RamblinDan** [comment]
@chrisanderberg Ok.  I've removed the extension and re-installed using the manual method.  That resolved the DI compilation error.  Definitely let me know if you figure out the issue with composer installation as I'd prefer to switch back to that.

**Comment by chrisanderberg** [comment]
@RamblinDan Reviewing some of your earlier comments, I noticed something which I overlooked earlier. The composer module is named "tealium/tags" and it seems that you described it as being installed in "tealium/tags" as opposed to "Tealium/Tags" (notice the case difference). I suspect Magento is expecting files in the uppercase form. Can you try renaming the directory to see if that makes a difference?

**Comment by RamblinDan** [comment]
@chrisanderberg To be clear, do you mean:

1. Revert the manual installation
2. Install via composer
3. If the directories are named "tealium/tags" rename them to "Tealium/Tags"?
4. Run the DI compilation process

**Comment by chrisanderberg** [comment]
@RamblinDan 

Yes, that's what I mean. I'm trying to determine if the naming is what caused the particular issue when installing via composer. If so it'll clue me into what I need to do to better support the extension out of box with composer. Unfortunately I struggled to reproduce the exact error you are getting so am relying on you to give me a bit more information. You may want to run with the verbose argument to see if you get extra useful information.

**Comment by gacek85** [comment]
There seem to be PSR4 mapping missing in composer.json in the autoload section.
```
"autoload": {
    "files": [ "registration.php" ],
    "psr-4": {
        "Tealium\\Tags\\": ""
    }
}
```

Temporary solution for people willing to solve it without reinstalling the module into app/code is to edit composer.lock after installing the module and add psr-4 entry in the autoload section. Then executing `composer install` will update autoloaders and the classes will start to load fine. Except other issue (not related with this) - Exception class in Udo missing \ (trailing slash) and are loaded from same namespace, which causes another error.

**Comment by gacek85** [comment]
I have just created a PR for solving this issue.
https://github.com/Tealium/integration-magento2/pull/6

**Comment by gacek85** [comment]
Can't this issue be closed after merging my fix? @chrisanderberg

**Comment by chrisanderberg** [comment]
@gacek85 Yes, forgot to close. Thanks
