### ISSUE TITLE
utag.view() call is triggered before utag.js is loaded on PDP

### ISSUE THREAD

**Issue by jeeshin** [Tealium/integration-magento2#25]
When loading a product page, there is a utag.view() call that is triggered before the utag.js library is loaded. This results in the error "utag is not defined". See below for the screenshot to see this illustrated.

<img width="1077" alt="utag-view" src="https://user-images.githubusercontent.com/39323851/63807246-30dd2f00-c8d2-11e9-81b0-af34ed6ca2d8.png">

The utag object needs to be defined on the page before utag.view() can be invoked.

Can the order of these Tealium-generated scripts be reversed, or can script dependencies be properly defined via RequireJS to prevent this scenario?

**Comment by short4bmoney** [comment]
Hi Jee. Thank you for calling this to our attention. We are actually in the middle of a significant update to the extension, so I will flag this for inclusion in the next release.

**Comment by jeeshin** [comment]
@short4bmoney Hi Brian, I wanted to follow up on this issue—has this been addressed in a published release? Also, where can I find up-to-date information on the latest releases? Thanks!
