### ISSUE TITLE
module.xml is missing

### ISSUE THREAD

**Issue by Fulmenef** [Tealium/integration-magento2#28]
Seems like some necessary files has been removed with the recent commit. Latest working is 799bc478ee77e4e869bc6ed98df047634dd829e1

**Step to reproduce**

1. Upgrade the module to the latest version.

**Expected behaviour**
`php bin/magento` display list of Magento 2 commands

**Current behaviour**
<img width="833" alt="Capture d’écran 2020-01-12 à 23 11 54" src="https://user-images.githubusercontent.com/17000257/72226399-ffb77f80-3590-11ea-9c14-03d88832d644.png">

**Comment by short4bmoney** [comment]
File has been restored. Closing this out.
