### ISSUE TITLE
Block and Controller duplicated

### ISSUE THREAD

**Issue by altie33** [Tealium/integration-magento2#30]
Hello,
I don't understand, why we have the folder Block and Controller duplicated ? So now we also have "Block 2" and 'Controller 2", with all the same files, and same namespace.
Also, where we can find release tag ? i don't understand why the latest tag is from 2018, how do you manage versions ?
Thank you.

**Comment by short4bmoney** [comment]
Hi @altie33 we are looking into this and will resolve soon. Thank you for raising the issue.
