### ISSUE TITLE
Error while adding Grouped product child to cart

### ISSUE THREAD

**Issue by girishanand** [Tealium/integration-magento2#42]
Hello @short4bmoney ,

There is an error while adding Grouped product item to cart and on the category page it break the product list page.
Created  [PR ](https://github.com/Tealium/integration-magento2/pull/43/) for the same.

**Comment by short4bmoney** [comment]
Hi @girishanand thank you for reporting this. We'll take a look and seek to fix with our current updates.

**Comment by short4bmoney** [comment]
Let us know if you continue to see any issues. This should be fixed with the latest merge.
