### ISSUE TITLE
Magento Checkout Tealium erros - seems increase checkout by 9 seconds 

### ISSUE THREAD

**Issue by jalexmendez** [Tealium/integration-magento2#44]
Hi all, hopefully you can help us with this high priority and visibility item.  We started getting this error in our logs. We actually started a support ticket with tealium but got referred to this github repo. 

`{
  "0": "Notice: Undefined index: cart in /home/jetrails/hydroflask.com/html/app/code/Tealium/Tags/Observer/UpdatePost.php on line 44",
  "1": "#1 Tealium\\Tags\\Observer\\UpdatePost->execute() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:88]\n
#2 Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod() called at [vendor/magento/framework/Event/Invoker/InvokerDefault.php:74]\n
#3 Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch() called at [vendor/magento/module-staging/Model/Event/Manager.php:97]\n
#4 Magento\\Staging\\Model\\Event\\Manager->dispatch() called at [generated/code/Magento/Staging/Model/Event/Manager/Proxy.php:95]\n
#5 Magento\\Staging\\Model\\Event\\Manager\\Proxy->dispatch() called at [vendor/magento/framework/App/Action/Action.php:101]\n
#6 Magento\\Framework\\App\\Action\\Action->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]\n
#7 Magento\\Checkout\\Controller\\Cart\\UpdatePost\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]\n
#8 Magento\\Checkout\\Controller\\Cart\\UpdatePost\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php:81]\n
#9 Magento\\CustomerSegment\\Model\\App\\Action\\ContextPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]\n
#10 Magento\\Checkout\\Controller\\Cart\\UpdatePost\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]\n
#11 Magento\\Checkout\\Controller\\Cart\\UpdatePost\\Interceptor->___callPlugins() called at [generated/code/Magento/Checkout/Controller/Cart/UpdatePost/Interceptor.php:39]\n
#12 Magento\\Checkout\\Controller\\Cart\\UpdatePost\\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:159]\n
#13 Magento\\Framework\\App\\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:99]\n
#14 Magento\\Framework\\App\\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]\n
#15 Magento\\Framework\\App\\FrontController\\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]\n
#16 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php:99]\n
#17 Magento\\Store\\App\\FrontController\\Plugin\\RequestPreprocessor->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]\n
#18 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php:69]\n
#19 Magento\\PageCache\\Model\\App\\FrontController\\BuiltinPlugin->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]\n
#20 Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]\n
#21 Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:26]\n
#22 Magento\\Framework\\App\\FrontController\\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]\n
#23 Magento\\Framework\\App\\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:261]\n
#24 Magento\\Framework\\App\\Bootstrap->run() called at [pub/index.php:50]\n
",
  "url": "/checkout/cart/updatePost/",
  "script_name": "/index.php",
  "report_id": "f7ded93f540823ea47323a9e990b20c816d72ea545b920988592e1d343ed75c1"
}`

And here is the New relic stack trace:
`in Magento\ConfigurableProduct\Helper\Product\Options\Loader::load called at /home/jetrails/hydroflask.com/html/vendor/magento/module-configurable-product/Model/Product/ReadHandler.php (48)
 in Magento\ConfigurableProduct\Model\Product\ReadHandler::execute called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/EntityManager/Operation/Read/ReadExtensions.php (48)
 in Magento\Framework\EntityManager\Operation\Read\ReadExtensions::execute called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/EntityManager/Operation/Read.php (112)
 in Magento\Framework\EntityManager\Operation\Read::execute called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/EntityManager/EntityManager.php (70)
 in Magento\Framework\EntityManager\EntityManager::load called at /home/jetrails/hydroflask.com/html/vendor/magento/module-catalog/Model/ResourceModel/Product.php (716)
 in Magento\Catalog\Model\ResourceModel\Product::load called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Model/AbstractModel.php (540)
 in Magento\Framework\Model\AbstractModel::load called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (58)
 in Magento\Catalog\Model\Product\Interceptor::___callParent called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (138)
 in Magento\Catalog\Model\Product\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (153)
 in Magento\Catalog\Model\Product\Interceptor::___callPlugins called at /home/jetrails/hydroflask.com/html/generated/code/Magento/Catalog/Model/Product/Interceptor.php (65)
 in Magento\Catalog\Model\Product\Interceptor::load called at /home/jetrails/hydroflask.com/html/app/code/Tealium/Tags/Controller/Cart/Index.php (53)
 in Tealium\Tags\Controller\Cart\Index::execute called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/App/Action/Action.php (108)
 in Magento\Framework\App\Action\Action::dispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (58)
 in Tealium\Tags\Controller\Cart\Index\Interceptor::___callParent called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (138)
 in Tealium\Tags\Controller\Cart\Index\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/module-customer-segment/Model/App/Action/ContextPlugin.php (81)
 in Magento\CustomerSegment\Model\App\Action\ContextPlugin::aroundDispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (135)
 in Tealium\Tags\Controller\Cart\Index\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (153)
 in Tealium\Tags\Controller\Cart\Index\Interceptor::___callPlugins called at /home/jetrails/hydroflask.com/html/generated/code/Tealium/Tags/Controller/Cart/Index/Interceptor.php (26)
 in Tealium\Tags\Controller\Cart\Index\Interceptor::dispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/App/FrontController.php (159)
 in Magento\Framework\App\FrontController::processRequest called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/App/FrontController.php (99)
 in Magento\Framework\App\FrontController::dispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (58)
 in Magento\Framework\App\FrontController\Interceptor::___callParent called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (138)
 in Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php (99)
 in Magento\Store\App\FrontController\Plugin\RequestPreprocessor::aroundDispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (135)
 in Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php (69)
 in Magento\PageCache\Model\App\FrontController\BuiltinPlugin::aroundDispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (135)
 in Magento\Framework\App\FrontController\Interceptor::Magento\Framework\Interception\{closure} called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/Interception/Interceptor.php (153)
 in Magento\Framework\App\FrontController\Interceptor::___callPlugins called at /home/jetrails/hydroflask.com/html/generated/code/Magento/Framework/App/FrontController/Interceptor.php (26)
 in Magento\Framework\App\FrontController\Interceptor::dispatch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/App/Http.php (116)
 in Magento\Framework\App\Http::launch called at /home/jetrails/hydroflask.com/html/vendor/magento/framework/App/Bootstrap.php (261)
 in Magento\Framework\App\Bootstrap::run called at /home/jetrails/hydroflask.com/html/pub/index.php (50)
`

Here are some of the screenshots of that issue:
![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/5596995/97033921-4fb07300-1521-11eb-864a-13d1dab3893b.png)
![tealium_async_generic](https://user-images.githubusercontent.com/5596995/97033925-50490980-1521-11eb-9b91-d2d9b0be8988.png)

**Comment by jalexmendez** [comment]
Hi do you have any comments or has anyone been able to review?

**Comment by short4bmoney** [comment]
Hi @jalexmendez. Thank you for reporting. We understand you are experiencing slow page load on checkout. Can you clarify what version of Magento 2 you are running? Can you also provide steps to reproduce? We don't benefit from running New Relic on our testing site(s), so we'll need more context in order to troubleshoot.

**Comment by jalexmendez** [comment]
Hi @short4bmoney ,

It was about 6K users to the checkout at one time during a Flash sale day.  The Magento version we have is Magento ver. 2.3.4-p2. The steps to reproduce are simple just going through a complete checkout.

Would this work what else can we do? We implemented this plugin around May-June.

Thank you,
Jaime

**Comment by jalexmendez** [comment]
Hi @short4bmoney , please let me know if you have an update. Would you be up for a quick meeting tomorrow?
thanks,
Jaime

**Comment by jalexmendez** [comment]
hi Brian,
Could you provide us with the latest Tealium plugin for Enterprise ?  We are going to update it but we want to make sure we are installing the correct version for our Magento ver. 2.3.4-p2 Enterprise framework.

Thank you,
Jaime

**Comment by onebricktech** [comment]
Hi https://github.com/jalexmendez
I am also a developer who supports this extension.
Can you let me know the product types you've added in cart?

**Comment by jalexmendez** [comment]
hi @short4bmoney (Brian) any updates? have you had a chance to review my comments?

thank you,
Jaime

**Comment by jalexmendez** [comment]
Hi ,

It would be mostly configurable products.  We are trying to update our
extension now, seems we might be outdated.. do you have a suggestion on
which version for the magento EE we have?

Thank you,
Jaime

**Comment by short4bmoney** [comment]
Hi @jalexmendez. We have not tested the plugin on Magento EE given the up-front costs for obtaining a license, but we are compatible on CE up to 2.4.x with the latest changes on this repo. Please note; the submission to the Magento Marketplace has not been made, which will soon reflect the updates on this repo.

**Comment by jalexmendez** [comment]
Thank you, we'll take the latest from this repo and test integration.
