### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'Tealium\Tags\Block\Exception' not found in /app/code/Tealium/Tags/Block/Udo.php:50

### ISSUE THREAD

**Issue by chuckdrew** [Tealium/integration-magento2#5]
Exception class is not defined

**Comment by chrisanderberg** [comment]
Hi @chuckdrew, may you describe how you encountered that issue so that I may attempt to recreate it?

**Comment by chuckdrew** [comment]
Hi @chrisanderberg 

A simple way to reproduce it is by visiting any Edge Side Include urls:

`http://www.yourmagentohost.com/page_cache/block/esi/blocks/["catalog.topnav"]/handles/["default","cms_index_index","cms_page_view","cms_index_index_id_home"]/`

Those are the urls that get embedded in the DOM when you are using the Varnish Full Page Cache.

Thanks!

Chuck

**Comment by chrisanderberg** [comment]
@chuckdrew can you bring this up in an email to support@tealium.com? I'd like to sort this out over a private channel if possible, and once the details are figured out we can circle back here and post the solution for others.

**Comment by chuckdrew** [comment]
Hey Chris,

We've got a hack in place that fixes the issue so no need to loop in support.

I believe there are two related issues for you to solve, both of which are not unique to me.

1. The exception class is missing. You need to add an exception class or you need to use fallbacks: http://php.net/manual/en/language.namespaces.fallback.php

2. The UDO should not be generated when loading ESI blocks. This is actually part of a much larger issue - the udo is part of the main page/request and gets cached by the default Magento Full Page Cache. It should be loaded asynchronously via ajax to avoid being cached...

Hope this helps :)

Thanks!

Chuck

**Comment by chrisanderberg** [comment]
Hi Chuck,

Would you mind posting a little info on your hack? Others who may have the same problem may find it useful, likewise it could help me create a fix.

Thanks,
Chris

**Comment by gacek85** [comment]
I have created a PR with simplest fix.
https://github.com/Tealium/integration-magento2/pull/7

**Comment by chrisanderberg** [comment]
@gacek85 Thanks for that. I'll test everything out and update.

**Comment by gacek85** [comment]
I guess this one can also be closed. @chrisanderberg
