### ISSUE TITLE
Magento 2.4.2 showing all results on search page and ignores pagination

### ISSUE THREAD

**Issue by pinfobeans** [Tealium/integration-magento2#52]
Hi,

Wen I enable the Tealium_Tags plugin on my Magento store, the search page's default functionality breaks. It shows all the products on same page and ignores pagination.
Rest all pages are working fine.

**Comment by rjshnautiyal** [comment]
Hi Team,

I am also facing same issue, category product listing page. Sorting filter & pagination not working and page showing all products.
Kindly let me know if there is any fix for this.
