### ISSUE TITLE
PHP 8.1 incompatibility

### ISSUE THREAD

**Issue by RedSign77** [Tealium/integration-magento2#55]
Hey Tealium!

Please add PHP 8.1 compatibility for this extension, because we will to use it for Magento 2.4.4.

Thank you,
Zoltán

**Comment by tegpe** [comment]
Hello, any plans of adding the compatibility of the PHP version 8.1, so that the latest versions of magento are supported by the module?

**Comment by artsiompearlconvert** [comment]
Hey Tealium!

Do you have any news here? Are you planning to upgrade the extension to Magento 2.4.5 and PHP 8.1?

**Comment by RedSign77** [comment]
I think this package is abandoned. :-(

**Comment by corbinspicer68** [comment]
In our latest version, PHP 8.1 is now supported along with First Party Domains.
