### ISSUE TITLE
Composer won't install with @RC

### ISSUE THREAD

**Issue by SAN1TAR1UM** [Tealium/integration-magento2#9]
Adding the composer dependency per the repos README results in the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tealium/tags @RC is satisfiable by tealium/tags[dev-master] but these conflict with your requirements or minimum-stability.
```
I did manage to get it to work using `"tealium/tags": "dev-master"` in the require block instead.

**Comment by tygavin** [comment]
closing as this integration was re-built
